---
language: java
dist: focal

jdk:
- openjdk11

notifications:
  email: true

branches:
  except:
  - gh-pages

cache:
  directories:
  - "$HOME/.m2"

env:
  global:
    - MVN_ARGS="--settings build/.travis.settings.xml"

stages:
  - name: Build-Test
  
# Uncomment these stages when you're ready to use them.
  - name: Semantic-Release
    if: (branch = main) AND (type IN (push, api)) AND (fork = false)
  - name: Publish-Release
    if: (tag IS present) AND (fork = false)

before_install:
  - sudo apt-get update
  - sudo apt-get install -y openjdk-8-jdk python3.8 python3-pip
  - curl https://pyenv.run | bash  # Install pyenv
  - export PATH="$HOME/.pyenv/bin:$PATH"
  - eval "$(pyenv init --path)"
  - eval "$(pyenv init -)"
  - sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java  # Set Java 11 explicitly
  - env | grep TRAVIS
  - pyenv install 3.8.12  # Install Python 3.8
  - pyenv global 3.8.12   # Set Python 3.8 globally

jobs:
  include:
    - stage: Build-Test
      jdk: openjdk11
      install: true
      script:
        - build/setMavenVersion.sh
        - mvn verify -fae -DskipITs $MVN_ARGS

    - jdk: openjdk17
      install: true
      script:
        - mvn verify -fae -DskipITs $MVN_ARGS

# Uncomment these stages when you're ready to use them.
    - stage: Semantic-Release
      install:
        - nvm install 14
        - npm install
        - pip install --user bump2version
      script:
        - npm run semantic-release

    - stage: Publish-Release
      jdk: openjdk11
      name: Publish-Javadoc
      install: true
      script:
        - build/setMavenVersion.sh
        - mvn clean javadoc:aggregate $MVN_ARGS
        - build/publishJavadoc.sh
      after_success:
        - echo "Javadocs successfully published to gh-pages!"

    - jdk: openjdk11
      name: Publish-To-Maven-Central
      install: true
      script:
        - build/setupSigning.sh
        - build/setMavenVersion.sh
        - mvn deploy $MVN_ARGS -DskipTests -P central
      after_success:
        - echo "Maven artifacts successfully published to Maven Central!"
